# Default values for cosi-driver-nutanix.
nameOverride: ""
fullnameOverride: ""

# cosi-driver-nutanix sidecar image.
image:
  registry: ghcr.io
  repository: nutanix-cloud-native/cosi-driver-nutanix
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

# Secret used by the cosi-driver-nutanix sidecar for objects management.
secret:
  enabled: true
  # Nutanix Object Store instance endpoint, eg. "http://10.51.142.82:80".
  endpoint: "http://10.38.185.135:80"
  # Admin IAM Access key to be used for Nutanix Objects.
  access_key: "8L8ajfXFKWnl8Tc-IFPetGiTDdCSCuHP"
  # Admin IAM Secret key to be used for Nutanix Objects.
  secret_key: "dX1Fho66s5yHFBaqt_fja5iPkrZtLgcs"
  # PC Credentials.
  pc_ip: "10.38.185.39"
  pc_port: "9440"
  pc_username: "admin"
  pc_password: "nx2Tech051!"
  # Account Name is a displayName identifier Prefix for Nutanix.
  # Objects to ensure that multiple requests for the same account
  # result in only one access token being created.
  # (Default_Prefix: ntnx-cosi-iam-user)
  account_name: "ntnx-cosi-iam-user"

# COSI central controller specifications.
cosiController:
  logLevel: 5
  image:
    registry: gcr.io
    repository: k8s-staging-sig-storage/objectstorage-controller
    tag: v20230524-v0.1.1-15-g5240fb3
    pullPolicy: Always

# COSI sidecar specifications.
objectstorageProvisionerSidecar:
  logLevel: 5
  image:
    registry: gcr.io
    repository: k8s-staging-sig-storage/objectstorage-sidecar/objectstorage-sidecar
    tag: v20221117-v0.1.0-22-g0e67387
    pullPolicy: Always
