apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: kube-system 
stringData:
  key: 10.42.80.37:9440:admin:nx2Tech109!    # << change this
  # example: 
  # key: 10.38.2.71:9440:admin:password
