
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot2
spec:
  volumeSnapshotClassName: acs-abs-snapshot-class
  source:
    persistentVolumeClaimName: mysql-pv-claimdemo
