apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ntnx
type: Opaque
stringData:
  # Nutanix Object Store instance endpoint, eg. "http://10.51.142.82:80"
  ENDPOINT: "http://10.38.185.135:80"
  # Admin IAM Access key to be used for Nutanix Objects
  ACCESS_KEY: "8L8ajfXFKWnl8Tc-IFPetGiTDdCSCuHP"
  # Admin IAM Secret key to be used for Nutanix Objects
  SECRET_KEY: "dX1Fho66s5yHFBaqt_fja5iPkrZtLgcs"
  # PC Credentials in format <prism-ip>:<prism-port>:<user>:<password>. 
  # eg. "10.51.142.125:9440:user:password"
  PC_SECRET: "10.38.185.39:9440:admin:nx2Tech051!"
  # Account Name is a displayName identifier Prefix for Nutanix 
  # Objects to ensure that multiple requests for the same account
  # result in only one access token being created
  # (Default_Prefix: ntnx-cosi-iam-user)
  ACCOUNT_NAME: ""
