apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{ include "ndb-operator.fullname" . }}-controller-manager
  name: {{ include "ndb-operator.fullname" . }}-controller-manager
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: {{ include "ndb-operator.fullname" . }}-controller-manager
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        control-plane: {{ include "ndb-operator.fullname" . }}-controller-manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end}}
      serviceAccountName: {{ include "ndb-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kube-rbac-proxy
          securityContext:
            allowPrivilegeEscalation: false
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
          args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=0
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          {{- with .Values.resources.kubeProxy }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: manager 
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: {{ .repository }}:{{ .tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources.controller }}
          resources: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
