apiVersion: v1
kind: ServiceAccount
metadata:
 name: mysql-dr-sa
 namespace: mysql-dr
secrets:
 - name: mysql-dr-sa-secret
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
 name: mysql-dr-sa-secret
 namespace: mysql-dr
 annotations:
   kubernetes.io/service-account.name: "mysql-dr-sa"

