{{- if eq .Values.createSecret true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  # base64 encoded prism-ip:prism-port:admin:password. 
  # E.g.: echo -n "10.83.0.91:9440:admin:mypassword" | base64
  key: {{ printf "%s:9440:%s:%s" .Values.prismEndPoint .Values.username .Values.password | b64enc}}
{{- end }}
---
{{- if eq .Values.createPrismCentralSecret true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pcSecretName }}
  namespace: {{ .Release.Namespace }}
data:
  # base64 encoded prism-ip:prism-port:admin:password. 
  # E.g.: echo -n "10.83.0.91:9440:admin:mypassword" | base64
  key: {{ printf "%s:9440:%s:%s" .Values.prismCentralEndPoint .Values.pcUsername .Values.pcPassword | b64enc}}
{{- end }}